In [3]:
import tensor
import numpy as np
from tensor.operation.generate import coil100_data, random_tensor

In [22]:
def stopping_criteria(original_tensor: np.ndarray, reconstructed_tensor: np.ndarray, P_hat: int, threshold=0.01) -> bool:
    '''
    This function is used to check if the tensor has converged.
    It randomly chooses P possible indices of original_tensor and new_tensor and compares the elements at those indices.
    '''
    # Randomly choose P indices
    indices = np.random.choice(original_tensor.size, P_hat, replace=False)
    print(original_tensor.size)
    # print elements at those indices
    # print(original_tensor.flat[indices])
    # print(indices)
    # print(new_tensor.flat[indices])
    
    original_tensor_elements = original_tensor.flat[indices]
    reconstructed_tensor_elements = reconstructed_tensor.flat[indices]
    
    # mean of squared difference
    mean_squared_difference = np.mean((original_tensor_elements - reconstructed_tensor_elements)**2)
    
    approx_epsilon = mean_squared_difference * original_tensor.size
    approx_epsilon = approx_epsilon**(1/2)

    relative_residual = approx_epsilon / np.linalg.norm(original_tensor)
    if relative_residual < threshold:
        return True
    
    return False

if __name__ == "__main__":
    l, w, s = 4, 12, 2
    for I in range(l, w, s):
        print(I)
        X  = random_tensor(3, (I,I,I), 7, 0.01)
        print(X)
        print("\n")
        if stopping_criteria(X, X, 10):
            break
        

4
[[[0.61724802 0.65393894 0.754655   0.63984463]
  [1.07485578 1.01199022 1.01761965 0.93291581]
  [1.58268054 1.72633482 1.85818028 1.78847835]
  [1.07493818 1.1198841  1.14825938 1.25326737]]

 [[0.19825413 0.32352649 0.36747439 0.353249  ]
  [0.38527488 0.54500479 0.61787421 0.67067902]
  [0.80206957 1.16862655 1.32765201 1.40650938]
  [0.74047299 1.00020476 1.06059615 1.27083152]]

 [[0.56593906 0.5789836  0.69723378 0.60666143]
  [0.97922819 0.78884946 0.82581163 0.82118484]
  [1.28186325 1.0939899  1.32401517 1.30920265]
  [1.14743279 1.18433825 1.2524223  1.50792897]]

 [[0.47402823 0.48486277 0.5260201  0.46115692]
  [0.84128286 0.77116283 0.78862791 0.73765819]
  [1.24238666 1.33184068 1.44139474 1.40422392]
  [0.78803863 0.76503951 0.82530033 0.89869828]]]


64
[1.01199022 0.5260201  1.0939899  1.32765201 0.82118484 1.33184068
 0.78884946 1.30920265 0.80206957 0.73765819]
[ 5 50 41 26 39 57 37 43 24 55]
[1.01199022 0.5260201  1.0939899  1.32765201 0.82118484 1.33184068
 0.78